#!/usr/bin/env bash
#define save dir for screenshots:
SAVE_DIR="$HOME/img/screenshots"

#Create directory if doesn't exist:
mkdir -p "$SAVE_DIR"

#create filename based on current time+date:
FILENAME="screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"
SAVEPATH="$SAVE_DIR/$FILENAME"

#take screenshot:
#slurp to select region/grim to capture and tee to save & copy
slurp | grim -g - "$SAVEPATH" && wl-copy <"$SAVEPATH"

#grim -g "$(slurp)" - | wl-copy
#notify-send "Screenshot copied to clipboard" -a "ss"
